# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: detect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='detect.proto',
  package='com.yimuzn.nutsdetection.device.grpc',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x64\x65tect.proto\x12$com.yimuzn.nutsdetection.device.grpc\"/\n\x0e\x43ommonResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x16\x41lgorithmConfigRequest\x12\x17\n\x0fmodel_file_path\x18\x01 \x01(\t\"$\n\x0c\x46rameRequest\x12\x14\n\x0corigin_frame\x18\x01 \x01(\x0c\"\x86\x02\n\rFrameResponse\x12\x17\n\x0fprocessed_frame\x18\x01 \x01(\x0c\x12\x11\n\thas_piece\x18\x02 \x01(\x08\x12\x14\n\x0cis_key_frame\x18\x03 \x01(\x08\x12X\n\x10part_result_list\x18\x04 \x03(\x0b\x32>.com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult\x1aY\n\nPartResult\x12\x0f\n\x07part_id\x18\x01 \x01(\t\x12\x11\n\tpart_code\x18\x02 \x01(\t\x12\x0f\n\x07nut_num\x18\x03 \x01(\x05\x12\x16\n\x0e\x66\x61\x63\x65_direction\x18\x04 \x01(\x05\x32\x99\x02\n\rDetectService\x12\x8b\x01\n\x15updateAlgorithmConfig\x12<.com.yimuzn.nutsdetection.device.grpc.AlgorithmConfigRequest\x1a\x34.com.yimuzn.nutsdetection.device.grpc.CommonResponse\x12z\n\x0bstreamVideo\x12\x32.com.yimuzn.nutsdetection.device.grpc.FrameRequest\x1a\x33.com.yimuzn.nutsdetection.device.grpc.FrameResponse(\x01\x30\x01\x62\x06proto3'
)




_COMMONRESPONSE = _descriptor.Descriptor(
  name='CommonResponse',
  full_name='com.yimuzn.nutsdetection.device.grpc.CommonResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='com.yimuzn.nutsdetection.device.grpc.CommonResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='com.yimuzn.nutsdetection.device.grpc.CommonResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=101,
)


_ALGORITHMCONFIGREQUEST = _descriptor.Descriptor(
  name='AlgorithmConfigRequest',
  full_name='com.yimuzn.nutsdetection.device.grpc.AlgorithmConfigRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_file_path', full_name='com.yimuzn.nutsdetection.device.grpc.AlgorithmConfigRequest.model_file_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=152,
)


_FRAMEREQUEST = _descriptor.Descriptor(
  name='FrameRequest',
  full_name='com.yimuzn.nutsdetection.device.grpc.FrameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin_frame', full_name='com.yimuzn.nutsdetection.device.grpc.FrameRequest.origin_frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=190,
)


_FRAMERESPONSE_PARTRESULT = _descriptor.Descriptor(
  name='PartResult',
  full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='part_id', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult.part_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='part_code', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult.part_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nut_num', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult.nut_num', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='face_direction', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult.face_direction', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=366,
  serialized_end=455,
)

_FRAMERESPONSE = _descriptor.Descriptor(
  name='FrameResponse',
  full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='processed_frame', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.processed_frame', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='has_piece', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.has_piece', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_key_frame', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.is_key_frame', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='part_result_list', full_name='com.yimuzn.nutsdetection.device.grpc.FrameResponse.part_result_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FRAMERESPONSE_PARTRESULT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=455,
)

_FRAMERESPONSE_PARTRESULT.containing_type = _FRAMERESPONSE
_FRAMERESPONSE.fields_by_name['part_result_list'].message_type = _FRAMERESPONSE_PARTRESULT
DESCRIPTOR.message_types_by_name['CommonResponse'] = _COMMONRESPONSE
DESCRIPTOR.message_types_by_name['AlgorithmConfigRequest'] = _ALGORITHMCONFIGREQUEST
DESCRIPTOR.message_types_by_name['FrameRequest'] = _FRAMEREQUEST
DESCRIPTOR.message_types_by_name['FrameResponse'] = _FRAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CommonResponse = _reflection.GeneratedProtocolMessageType('CommonResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMMONRESPONSE,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:com.yimuzn.nutsdetection.device.grpc.CommonResponse)
  })
_sym_db.RegisterMessage(CommonResponse)

AlgorithmConfigRequest = _reflection.GeneratedProtocolMessageType('AlgorithmConfigRequest', (_message.Message,), {
  'DESCRIPTOR' : _ALGORITHMCONFIGREQUEST,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:com.yimuzn.nutsdetection.device.grpc.AlgorithmConfigRequest)
  })
_sym_db.RegisterMessage(AlgorithmConfigRequest)

FrameRequest = _reflection.GeneratedProtocolMessageType('FrameRequest', (_message.Message,), {
  'DESCRIPTOR' : _FRAMEREQUEST,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:com.yimuzn.nutsdetection.device.grpc.FrameRequest)
  })
_sym_db.RegisterMessage(FrameRequest)

FrameResponse = _reflection.GeneratedProtocolMessageType('FrameResponse', (_message.Message,), {

  'PartResult' : _reflection.GeneratedProtocolMessageType('PartResult', (_message.Message,), {
    'DESCRIPTOR' : _FRAMERESPONSE_PARTRESULT,
    '__module__' : 'detect_pb2'
    # @@protoc_insertion_point(class_scope:com.yimuzn.nutsdetection.device.grpc.FrameResponse.PartResult)
    })
  ,
  'DESCRIPTOR' : _FRAMERESPONSE,
  '__module__' : 'detect_pb2'
  # @@protoc_insertion_point(class_scope:com.yimuzn.nutsdetection.device.grpc.FrameResponse)
  })
_sym_db.RegisterMessage(FrameResponse)
_sym_db.RegisterMessage(FrameResponse.PartResult)



_DETECTSERVICE = _descriptor.ServiceDescriptor(
  name='DetectService',
  full_name='com.yimuzn.nutsdetection.device.grpc.DetectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=458,
  serialized_end=739,
  methods=[
  _descriptor.MethodDescriptor(
    name='updateAlgorithmConfig',
    full_name='com.yimuzn.nutsdetection.device.grpc.DetectService.updateAlgorithmConfig',
    index=0,
    containing_service=None,
    input_type=_ALGORITHMCONFIGREQUEST,
    output_type=_COMMONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='streamVideo',
    full_name='com.yimuzn.nutsdetection.device.grpc.DetectService.streamVideo',
    index=1,
    containing_service=None,
    input_type=_FRAMEREQUEST,
    output_type=_FRAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DETECTSERVICE)

DESCRIPTOR.services_by_name['DetectService'] = _DETECTSERVICE

# @@protoc_insertion_point(module_scope)
